create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 32),
  message text not null check (char_length(message) between 1 and 420),
  created_at timestamptz not null default now()
);

alter table public.forum_posts enable row level security;

drop policy if exists "Forum posts are readable" on public.forum_posts;
create policy "Forum posts are readable"
on public.forum_posts
for select
to anon
using (true);

drop policy if exists "Visitors can add forum posts" on public.forum_posts;
create policy "Visitors can add forum posts"
on public.forum_posts
for insert
to anon
with check (
  char_length(name) between 1 and 32
  and char_length(message) between 1 and 420
);

create index if not exists forum_posts_created_at_idx
on public.forum_posts (created_at desc);
